export interface CategorySeed {
  name: string;
  slug: string;
  description: string;
  icon: string;
}

export const INITIAL_CATEGORIES: CategorySeed[] = [
  { name: 'Technology', slug: 'technology', description: 'Computing, modern software, consumer electronics, and engineering paradigms.', icon: 'Cpu' },
  { name: 'Artificial Intelligence', slug: 'artificial-intelligence', description: 'Machine learning, neural networks, LLMs, vision, and cognitive systems.', icon: 'Bot' },
  { name: 'Programming', slug: 'programming', description: 'Code architecture, developer tools, algorithms, and languages.', icon: 'Code' },
  { name: 'Science', slug: 'science', description: 'Physics, chemistry, biology, earth sciences, and empirical research.', icon: 'Atom' },
  { name: 'Mathematics', slug: 'mathematics', description: 'Pure math, applied statistics, calculus, discrete systems, and algebra.', icon: 'Binary' },
  { name: 'Education', slug: 'education', description: 'Pedagogy, academia, higher learning, and study methodologies.', icon: 'GraduationCap' },
  { name: 'Careers', slug: 'careers', description: 'Professional growth, mentorship, transitions, and industry navigation.', icon: 'Briefcase' },
  { name: 'Jobs', slug: 'jobs', description: 'Hiring, technical interviews, resumes, workplaces, and compensation.', icon: 'Compass' },
  { name: 'Business', slug: 'business', description: 'Corporate strategy, operations, leadership, and modern organizational systems.', icon: 'Building2' },
  { name: 'Finance', slug: 'finance', description: 'Capital markets, banking, macroeconomic policy, and accounting.', icon: 'BadgeDollarSign' },
  { name: 'Investing', slug: 'investing', description: 'Equities, index funds, asset allocation, portfolio risk, and long-term wealth.', icon: 'TrendingUp' },
  { name: 'Entrepreneurship', slug: 'entrepreneurship', description: 'Bootstrapping, venture-backed startups, product-market fit, and scaling.', icon: 'Rocket' },
  { name: 'History', slug: 'history', description: 'Ancient civilizations, world conflicts, cultural shifts, and historiography.', icon: 'Scroll' },
  { name: 'Geography', slug: 'geography', description: 'Cartography, geopolitical borders, topography, climate zones, and territories.', icon: 'Globe' },
  { name: 'Politics', slug: 'politics', description: 'Governance, democratic institutions, public policy, and civic affairs.', icon: 'Landmark' },
  { name: 'Law', slug: 'law', description: 'Jurisprudence, constitutional rights, international treaties, and contracts.', icon: 'Scale' },
  { name: 'Psychology', slug: 'psychology', description: 'Cognitive behavior, neuropsychology, human perception, and mental health.', icon: 'Brain' },
  { name: 'Philosophy', slug: 'philosophy', description: 'Epistemology, ethics, logic, existential inquiry, and moral frameworks.', icon: 'BookOpen' },
  { name: 'Relationships', slug: 'relationships', description: 'Interpersonal dynamics, communication, empathy, and social psychology.', icon: 'HeartHandshake' },
  { name: 'Parenting', slug: 'parenting', description: 'Child development, family education, health, and supportive upbringing.', icon: 'Users' },
  { name: 'Health', slug: 'health', description: 'Preventive medicine, physiology, healthcare systems, and wellness science.', icon: 'Activity' },
  { name: 'Fitness', slug: 'fitness', description: 'Strength training, cardiovascular conditioning, ergonomics, and mobility.', icon: 'Dumbbell' },
  { name: 'Nutrition', slug: 'nutrition', description: 'Dietary science, macronutrients, metabolic pathways, and food biology.', icon: 'Apple' },
  { name: 'Travel', slug: 'travel', description: 'Global expeditions, travel itineraries, cultural exploration, and logistics.', icon: 'Plane' },
  { name: 'Food', slug: 'food', description: 'Culinary traditions, ingredients, gastronomy, and international cuisines.', icon: 'Utensils' },
  { name: 'Cooking', slug: 'cooking', description: 'Culinary technique, baking science, kitchen craft, and recipe formulation.', icon: 'Flame' },
  { name: 'Movies', slug: 'movies', description: 'Cinema, directing, cinematography, film theory, and screenwriting.', icon: 'Film' },
  { name: 'Television', slug: 'television', description: 'Serialized storytelling, broadcast production, and streaming culture.', icon: 'Tv' },
  { name: 'Music', slug: 'music', description: 'Acoustics, music theory, composition, audio engineering, and discographies.', icon: 'Music' },
  { name: 'Books', slug: 'books', description: 'Literature, critical reading, publishing, fiction, and essay collections.', icon: 'Book' },
  { name: 'Gaming', slug: 'gaming', description: 'Game design, interactive mechanics, esports, and interactive media.', icon: 'Gamepad2' },
  { name: 'Sports', slug: 'sports', description: 'Athletics, competitive leagues, sports analytics, and performance.', icon: 'Trophy' },
  { name: 'Cars', slug: 'cars', description: 'Automotive engineering, electric drivetrains, manufacturing, and mechanics.', icon: 'Car' },
  { name: 'Motorcycles', slug: 'motorcycles', description: 'Two-wheeled dynamics, rider mechanics, tours, and engine builds.', icon: 'Gauge' },
  { name: 'Photography', slug: 'photography', description: 'Optics, exposure science, lighting, darkroom craft, and visual critique.', icon: 'Camera' },
  { name: 'Art', slug: 'art', description: 'Fine art, historical movements, sculpture, gallery curation, and aesthetics.', icon: 'Palette' },
  { name: 'Design', slug: 'design', description: 'Industrial design, typography, systems architecture, and UX ethics.', icon: 'Layers' },
  { name: 'Fashion', slug: 'fashion', description: 'Textiles, garment construction, historical garments, and modern silhouettes.', icon: 'Shirt' },
  { name: 'Beauty', slug: 'beauty', description: 'Dermatology, skincare chemistry, cosmetics science, and care routines.', icon: 'Sparkles' },
  { name: 'Animals', slug: 'animals', description: 'Zoology, wildlife conservation, behavioral biology, and habitats.', icon: 'Footprints' },
  { name: 'Pets', slug: 'pets', description: 'Veterinary care, pet socialization, canine & feline care, and training.', icon: 'Dog' },
  { name: 'Nature', slug: 'nature', description: 'Ecology, biodiversity, forest conservation, and environmental systems.', icon: 'TreePine' },
  { name: 'Space', slug: 'space', description: 'Astrophysics, planetary science, orbital mechanics, and space missions.', icon: 'Telescope' },
  { name: 'Languages', slug: 'languages', description: 'Linguistics, etymology, language acquisition, and translation systems.', icon: 'Languages' },
  { name: 'Culture', slug: 'culture', description: 'Anthropology, folklore, social rituals, and heritage preservation.', icon: 'Glasses' },
  { name: 'Lifestyle', slug: 'lifestyle', description: 'Intentional living, daily routines, habits, and sustainable practices.', icon: 'Coffee' },
  { name: 'DIY', slug: 'diy', description: 'Woodworking, electronics tinkering, repairs, and fabrication.', icon: 'Wrench' },
  { name: 'Home', slug: 'home', description: 'Interior architecture, domestic ergonomics, lighting, and upkeep.', icon: 'Home' },
  { name: 'Shopping', slug: 'shopping', description: 'Consumer guidance, durable goods, product reviews, and value evaluation.', icon: 'ShoppingBag' },
  { name: 'General', slug: 'general', description: 'Open inquiries, curiosity, interdisciplinary questions, and civil discourse.', icon: 'HelpCircle' }
];
